# Generated by Django 3.2.12 on 2022-05-21 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0002_team'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='img',
            new_name='img1',
        ),
        migrations.RenameField(
            model_name='team',
            old_name='name',
            new_name='name1',
        ),
        migrations.AddField(
            model_name='team',
            name='desc1',
            field=models.TextField(default=1771991),
            preserve_default=False,
        ),
    ]
